name: Static AWS workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "static" branch
  push:
    branches: [static.aws]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: '20.11.1'
          cache: 'yarn'

      - name: Build static
        env:
          PUBLIC_APP_NAME: ${{ vars.PUBLIC_APP_NAME }}
          PUBLIC_APP_DOMAIN: ${{ vars.PUBLIC_APP_DOMAIN }}
          PRIVATE_ENCRYPT_KEY: ${{ vars.PRIVATE_ENCRYPT_KEY }}

        run: |
          yarn
          yarn build

      # https://github.com/marketplace/actions/s3-sync
      - name: Sync and upload to AWS bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_S3_ENDPOINT: ${{ vars.AWS_S3_ENDPOINT }}
          AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          SOURCE_DIR: './build'
